const CHECK_SIGN_IN = 'CHECK_SIGN_IN';
const CHECK_REGISTER = 'CHECK_REGISTER';
const LOADING_CHECK = 'LOADING_CHECK';

const CLEAR_REDUX_ERRORS = 'CLEAR_REDUX_ERRORS'

const SEND_AUTHENTICATED_FROM_REDUX_TO_SAGA = 'SEND_AUTHENTICATED_FROM_REDUX_TO_SAGA';

const DATABASE_ERROR_FROM_REDUX_TO_SAGA = 'DATABASE_ERROR_FROM_REDUX_TO_SAGA';

const REGISTER_EMAIL_ERROR_FROM_REDUX_TO_SAGA = 'REGISTER_EMAIL_ERROR_FROM_REDUX_TO_SAGA';
const REGISTER_NAME_ERROR_FROM_REDUX_TO_SAGA = 'REGISTER_NAME_ERROR_FROM_REDUX_TO_SAGA';

const LOGIN_NAME_EMAIL_ERROR_FROM_REDUX_TO_SAGA = 'LOGIN_NAME_EMAIL_ERROR_FROM_REDUX_TO_SAGA';
const LOGIN_PASSWORD_ERROR_FROM_REDUX_TO_SAGA = 'LOGIN_PASSWORD_ERROR_FROM_REDUX_TO_SAGA';

const LOGOUT = 'LOGOUT';
const LOGOUT_FROM_REDUX_TO_SAGA = 'LOGOUT_FROM_REDUX_TO_SAGA';

export {
  CHECK_SIGN_IN,
  SEND_AUTHENTICATED_FROM_REDUX_TO_SAGA,
  CHECK_REGISTER,
  DATABASE_ERROR_FROM_REDUX_TO_SAGA,
  REGISTER_EMAIL_ERROR_FROM_REDUX_TO_SAGA,
  REGISTER_NAME_ERROR_FROM_REDUX_TO_SAGA,
  LOGIN_NAME_EMAIL_ERROR_FROM_REDUX_TO_SAGA,
  LOGIN_PASSWORD_ERROR_FROM_REDUX_TO_SAGA,
  LOADING_CHECK,
  CLEAR_REDUX_ERRORS,
  LOGOUT,
  LOGOUT_FROM_REDUX_TO_SAGA
}
