const CHECK_SIGN_IN = 'CHECK_SIGN_IN';
const CHECK_REGISTER = 'CHECK_REGISTER';
const LOADING_CHECK = 'LOADING_CHECK';

const SEND_AUTHENTICATED_FROM_SAGA_TO_REDUX = 'SEND_AUTHENTICATED_FROM_SAGA_TO_REDUX'; // ++

const DATABASE_ERROR_FROM_SAGA_TO_REDUX = 'DATABASE_ERROR_FROM_SAGA_TO_REDUX'; // ++

const REGISTER_EMAIL_ERROR_FROM_SAGA_TO_REDUX = 'REGISTER_EMAIL_ERROR_FROM_SAGA_TO_REDUX'; // ++
const REGISTER_NAME_ERROR_FROM_SAGA_TO_REDUX = 'REGISTER_NAME_ERROR_FROM_SAGA_TO_REDUX'; // ++

const LOGIN_NAME_EMAIL_ERROR_FROM_SAGA_TO_REDUX = 'LOGIN_NAME_EMAIL_ERROR_FROM_SAGA_TO_REDUX'; // ++
const LOGIN_PASSWORD_ERROR_FROM_SAGA_TO_REDUX = 'LOGIN_PASSWORD_ERROR_FROM_SAGA_TO_REDUX'; // ++

const LOGOUT = 'LOGOUT';
const LOGOUT_FROM_SAGA_TO_REDUX = 'LOGOUT_FROM_SAGA_TO_REDUX'; // ++

const LOAD_THREADS = 'LOAD_THREADS';
const LOAD_THREADS_FROM_SAGA_TO_REDUX = 'LOAD_THREADS_FROM_SAGA_TO_REDUX'; // ++

const LOAD_DEBATES = 'LOAD_DEBATES';
const LOAD_DEBATES_FROM_SAGA_TO_REDUX = 'LOAD_DEBATES_FROM_SAGA_TO_REDUX'; // ++

const CREATE_NEW_THREAD = 'CREATE_NEW_THREAD';
const CREATE_NEW_THREAD_FROM_SAGA_TO_REDUX = 'CREATE_NEW_THREAD_FROM_SAGA_TO_REDUX';
const CHECK_CREATED_THREAD = 'CHECK_CREATED_THREAD';

const CREATE_NEW_DEBATE = 'CREATE_NEW_DEBATE';
const CREATE_NEW_DEBATE_FROM_SAGA_TO_REDUX = 'CREATE_NEW_DEBATE_FROM_SAGA_TO_REDUX';

const ADD_LIKE_TO_USER_IN_REDUX = 'ADD_LIKE_TO_USER_IN_REDUX';
const ADD_COMMENT_TO_USER_IN_REDUX ='ADD_COMMENT_TO_USER_IN_REDUX';
const ADD_COMMENT_COUNT_TO_COMMENTS_IN_REDUX = 'ADD_COMMENT_COUNT_TO_COMMENTS_IN_REDUX';

const CHANGE_COMMET_WRITING_PERMISSON = 'CHANGE_COMMET_WRITING_PERMISSON';
const SET_COMMENT_WRITING_COOLDOWN = 'SET_COMMENT_WRITING_COOLDOWN';


export {
  CHECK_SIGN_IN,
  SEND_AUTHENTICATED_FROM_SAGA_TO_REDUX,
  CHECK_REGISTER,
  DATABASE_ERROR_FROM_SAGA_TO_REDUX,
  REGISTER_EMAIL_ERROR_FROM_SAGA_TO_REDUX,
  REGISTER_NAME_ERROR_FROM_SAGA_TO_REDUX,
  LOGIN_NAME_EMAIL_ERROR_FROM_SAGA_TO_REDUX,
  LOGIN_PASSWORD_ERROR_FROM_SAGA_TO_REDUX,
  LOADING_CHECK,
  LOGOUT,
  LOGOUT_FROM_SAGA_TO_REDUX,
  LOAD_THREADS,
  LOAD_THREADS_FROM_SAGA_TO_REDUX,
  LOAD_DEBATES,
  LOAD_DEBATES_FROM_SAGA_TO_REDUX,
  CREATE_NEW_THREAD,
  CREATE_NEW_THREAD_FROM_SAGA_TO_REDUX,
  CREATE_NEW_DEBATE,
  CREATE_NEW_DEBATE_FROM_SAGA_TO_REDUX,
  CHECK_CREATED_THREAD,
  ADD_COMMENT_TO_USER_IN_REDUX,
  ADD_LIKE_TO_USER_IN_REDUX,
  CHANGE_COMMET_WRITING_PERMISSON,
  SET_COMMENT_WRITING_COOLDOWN,
  ADD_COMMENT_COUNT_TO_COMMENTS_IN_REDUX,
}
